exclude:
  - "/vendor/"
  - "/_drafts/"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - ".idea/"
  - "Makefile"


keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Codesai
url: https://www.codesai.com
cover: "/assets/cover.png"
logo: "/assets/logo.png"
permalink: /posts/:year/:month/:title

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: G-5HTPFFFN4L

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

environment: production

languages: ["es", "en"] # First language is default
exclude_from_localizations: ["javascript", "css", "sass", "img", "fonts", "js", "scripts"]

plugins:
  - jekyll-multiple-languages-plugin