environment: development

languages: ["es", "en"] # First language is default

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-compress-images

compress_images:
  images_path: "assets/**/*.{gif,png,jpg,jpeg,svg}"
